# Generated by Django 5.2.6 on 2025-11-02 15:48

import django.core.validators
import django.db.models.deletion
import neonatos.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.AutoField(db_column='id_madre', primary_key=True, serialize=False)),
                ('rut', models.CharField(help_text='RUT con guion y DV (ej: 12.345.678-5)', max_length=12, unique=True, validators=[neonatos.validators.rut_chile_validator], verbose_name='RUT')),
                ('nombres', models.CharField(help_text='Solo letras y espacios.', max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Solo letras y espacios.', max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, help_text='Opcional', max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('edad', models.PositiveIntegerField(help_text='Años cumplidos.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)], verbose_name='Edad')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('pueblo_originario', models.CharField(max_length=50, verbose_name='Pertenece a pueblo originario')),
                ('discapacidad', models.CharField(max_length=50, verbose_name='Discapacidad con credencial SENADIS')),
                ('privada_libertad', models.CharField(max_length=50, verbose_name='Privada de libertad')),
                ('controles_prenatales', models.CharField(max_length=50, verbose_name='Controles prenatales')),
            ],
            options={
                'verbose_name': 'Madre',
                'verbose_name_plural': 'Madres',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_parto', models.DateField(verbose_name='Fecha del parto')),
                ('tipo_parto', models.CharField(choices=[('vaginal', 'Vaginal'), ('instrumental', 'Instrumental'), ('cesarea_electiva', 'Cesárea electiva'), ('cesarea_urgencia', 'Cesárea de urgencia'), ('domicilio', 'Parto en domicilio'), ('prehospitalario', 'Prehospitalario')], max_length=20, verbose_name='Tipo de parto')),
                ('inicio_parto', models.CharField(blank=True, choices=[('espontaneo', 'Espontáneo'), ('inducido', 'Inducido')], max_length=12, verbose_name='Inicio de parto')),
                ('analgesia', models.CharField(blank=True, choices=[('neuroaxial', 'Neuroaxial'), ('endovenosa', 'Endovenosa'), ('oxido_nitroso', 'Óxido nitroso'), ('general', 'General'), ('local', 'Local'), ('no_farmacologica', 'No farmacológica')], max_length=20, verbose_name='Analgesia')),
                ('acompanamiento', models.CharField(blank=True, choices=[('ninguno', 'Ninguno'), ('trabajo_parto', 'Trabajo de parto'), ('expulsivo', 'Expulsivo')], max_length=20, verbose_name='Acompañamiento')),
                ('episiotomia', models.BooleanField(default=False, verbose_name='Episiotomía')),
                ('oxitocina', models.BooleanField(default=False, verbose_name='Oxitocina profiláctica')),
                ('plan_parto', models.BooleanField(default=False, verbose_name='Plan de parto registrado')),
                ('contacto_piel_piel', models.BooleanField(default=False, verbose_name='Contacto piel con piel')),
                ('alojamiento_conjunto', models.BooleanField(default=False, verbose_name='Alojamiento conjunto')),
                ('cesarea_programada', models.BooleanField(default=False, verbose_name='Cesárea programada')),
                ('edad_gestacional', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)], verbose_name='Edad gestacional (semanas)')),
                ('complicaciones', models.BooleanField(default=False, verbose_name='Complicaciones')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='neonatos.madre')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Matrona responsable')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
            },
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, help_text='Formato: D o D.ddd (ej: 3.256). Máximo 9.999', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('9.999'))], verbose_name='Peso del recién nacido (kg)')),
                ('talla', models.PositiveIntegerField(verbose_name='Talla (cm)')),
                ('apgar_1', models.IntegerField(blank=True, null=True, verbose_name='Puntuación Apgar (1 min)')),
                ('apgar_5', models.IntegerField(blank=True, null=True, verbose_name='Puntuación Apgar (5 min)')),
                ('anomalias_congenitas', models.BooleanField(default=False, verbose_name='Anomalías congénitas')),
                ('profilaxis_hepatitisb', models.BooleanField(default=False, verbose_name='Profilaxis Hepatitis B')),
                ('profilaxis_ocular', models.BooleanField(default=False, verbose_name='Profilaxis ocular')),
                ('reanimacion', models.CharField(choices=[('ninguna', 'Ninguna'), ('basica', 'Básica'), ('avanzada', 'Avanzada')], default='ninguna', max_length=10, verbose_name='Reanimación')),
                ('asfixia_neonatal', models.BooleanField(default=False, verbose_name='Asfixia neonatal')),
                ('tamizaje_metabolico', models.BooleanField(default=False, verbose_name='Tamizaje metabólico')),
                ('tamizaje_auditivo', models.BooleanField(default=False, verbose_name='Tamizaje auditivo')),
                ('tamizaje_cardiaco', models.BooleanField(default=False, verbose_name='Tamizaje cardíaco')),
                ('fallecido', models.BooleanField(default=False, verbose_name='Fallecido')),
                ('tipo_fallecimiento', models.CharField(blank=True, choices=[('aborto', 'Aborto'), ('mortinato', 'Mortinato'), ('mortineonato', 'Mortineonato')], max_length=20, null=True, verbose_name='Tipo de fallecimiento')),
                ('metodo_alimentacion', models.CharField(blank=True, choices=[('LME', 'LME (Lactancia Materna Exclusiva)'), ('mixta', 'Mixta'), ('formula', 'Fórmula'), ('no_amamantado', 'No amamantado'), ('HTLV_VIH', 'HTLV/VIH'), ('Ley21155', 'Ley 21.155')], max_length=20, null=True, verbose_name='Método de alimentación')),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='neonatos.parto')),
            ],
            options={
                'verbose_name': 'Recién nacido',
                'verbose_name_plural': 'Recién nacidos',
            },
        ),
    ]
