# Generated by Django 5.2.6 on 2025-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='cesareas_previas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='madre',
            name='paridad',
            field=models.CharField(choices=[('nulipara', 'Nulípara'), ('multipara', 'Multípara')], default='nulipara', max_length=20),
        ),
        migrations.AddField(
            model_name='parto',
            name='embarazo_multiple',
            field=models.BooleanField(default=False, verbose_name='Embarazo múltiple'),
        ),
        migrations.AddField(
            model_name='parto',
            name='hora_parto',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del parto'),
        ),
        migrations.AddField(
            model_name='parto',
            name='presentacion_fetal',
            field=models.CharField(blank=True, choices=[('cefalica', 'Cefálica'), ('pelvica', 'Pélvica'), ('transversa', 'Transversa')], max_length=20, null=True, verbose_name='Presentación fetal'),
        ),
        migrations.AddField(
            model_name='parto',
            name='tipo_atencion',
            field=models.CharField(choices=[('programada', 'Programada'), ('urgencia', 'Urgencia')], default='programada', max_length=20, verbose_name='Tipo de atención'),
        ),
    ]
