# Generated by Django 5.2.6 on 2025-11-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parto',
            name='registrado_por',
        ),
    ]
