# Generated by Django 5.2.6 on 2025-11-17 21:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_roles', '0002_remove_parto_registrado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('valido_hasta', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
