# Generated by Django 5.2.6 on 2025-10-30 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id_madre', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('pueblo_originario', models.BooleanField()),
                ('discapacidad', models.BooleanField()),
                ('privada_libertad', models.BooleanField()),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('controles_prenatales', models.BooleanField()),
            ],
            options={
                'db_table': 'madre',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id_parto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_parto', models.DateField()),
                ('tipo_parto', models.CharField(max_length=50)),
                ('inicio_parto', models.CharField(blank=True, max_length=20, null=True)),
                ('analgesia', models.CharField(blank=True, max_length=50, null=True)),
                ('acompanamiento', models.CharField(blank=True, max_length=30, null=True)),
                ('episiotomia', models.BooleanField()),
                ('oxitocina', models.BooleanField()),
                ('plan_parto', models.BooleanField()),
                ('contacto_piel_piel', models.BooleanField()),
                ('alojamiento_conjunto', models.BooleanField()),
                ('cesarea_programada', models.BooleanField()),
                ('edad_gestacional', models.IntegerField()),
                ('complicaciones', models.BooleanField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_madre', models.ForeignKey(db_column='id_madre', on_delete=django.db.models.deletion.CASCADE, to='GeneradorReporte.madre')),
            ],
            options={
                'db_table': 'parto',
            },
        ),
        migrations.CreateModel(
            name='Complicacion',
            fields=[
                ('id_complicacion', models.AutoField(primary_key=True, serialize=False)),
                ('hemorragia_postparto', models.BooleanField()),
                ('preeclampsia_eclampsia', models.BooleanField()),
                ('sepsis', models.BooleanField()),
                ('otras_complicaciones', models.TextField(blank=True, null=True)),
                ('transfusion_sanguinea', models.BooleanField()),
                ('histerectomia', models.BooleanField()),
                ('traslado_uci', models.BooleanField()),
                ('id_parto', models.ForeignKey(db_column='id_parto', on_delete=django.db.models.deletion.CASCADE, to='GeneradorReporte.parto')),
            ],
            options={
                'db_table': 'complicacion',
            },
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id_rn', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=15)),
                ('peso_nacer', models.DecimalField(decimal_places=1, max_digits=5)),
                ('apgar_1', models.IntegerField()),
                ('apgar_5', models.IntegerField()),
                ('anomalias_congenitas', models.BooleanField()),
                ('profilaxis_hepatitisb', models.BooleanField()),
                ('profilaxis_ocular', models.BooleanField()),
                ('reanimacion', models.CharField(max_length=20)),
                ('asfixia_neonatal', models.BooleanField()),
                ('tamizaje_metabolico', models.BooleanField()),
                ('tamizaje_auditivo', models.BooleanField()),
                ('tamizaje_cardiaco', models.BooleanField()),
                ('fallecido', models.BooleanField()),
                ('tipo_fallecimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('metodo_alimentacion', models.CharField(blank=True, max_length=20, null=True)),
                ('id_parto', models.ForeignKey(db_column='id_parto', on_delete=django.db.models.deletion.CASCADE, to='GeneradorReporte.parto')),
            ],
            options={
                'db_table': 'recien_nacido',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='GeneradorReporte.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='parto',
            name='registrado_por',
            field=models.ForeignKey(db_column='registrado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneradorReporte.usuario'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneradorReporte.usuario')),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
    ]
